require 'rearmed/monkey_patches/rails/active_record/base'
require 'rearmed/monkey_patches/rails/active_record/batches'
require 'rearmed/monkey_patches/rails/active_record/query_methods'
require 'rearmed/monkey_patches/rails/helpers'
require 'rearmed/monkey_patches/rails/v3'
require 'rearmed/monkey_patches/minitest'
